apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
  - image: gcr.io/slchase-canary/ahab-publisher
    jib:
      args:
      - -DskipTests
manifests:
  rawYaml:
  - k8s/dev*
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - image: gcr.io/slchase-canary/ahab-publisher
      jib: {}
    tagPolicy:
      sha256: {}
  manifests:
    rawYaml:
    - k8s/dev/*
  deploy:
    kubectl: {}
